from .nodes.dummy_node import NODE_CLASS_MAPPINGS as DUMMY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DUMMY_DISPLAY_MAPPINGS
from .nodes.openai_node import NODE_CLASS_MAPPINGS as OPENAI_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OPENAI_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**DUMMY_MAPPINGS, **OPENAI_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**DUMMY_DISPLAY_MAPPINGS, **OPENAI_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']